brokerUrl: tcp://127.0.0.1:1883
username: user-002
password: 1234
clientid: 90dabd46-d377-4e07-a119-414a358ee03d
measurements:
    - name: stats
      fields:
        - name: oilTemperature
          type: Integer
        - name: earthinVoltage
          type: Integer
        - name: operationMode
          type: Integer
      frequency: 1000
      type: RANDOM